version: 0.2
env:
  variables:
    TWINE_USERNAME: __token__
  secrets-manager:
    TWINE_PASSWORD: aws-emr-launch-deployment-secrets:PyPiApiKey
phases:
  install:
    runtime-versions:
      python: 3.7
      nodejs: 12
    commands:
      - python3 -m venv .venv
      - . .venv/bin/activate
      - pip install -r requirements-dev.txt
      - pip install -r requirements-1.5.x.txt
      - pip install -r requirements-lambda-layer.txt --target=aws_emr_launch/lambda_sources/layers/emr_config_utils/python/lib/python3.7/site-packages/
      - pip install -e .
  pre_build:
    commands:
      - . .venv/bin/activate
      - pytest
  build:
    commands:
      - . .venv/bin/activate
      - python setup.py bdist_wheel
  post_build:
    commands:
      - twine upload dist/*
artifacts:
  files:
    - dist/**/*
  discard-paths: yes
